# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 826c03b3fcc2e5b83212f99aee53d8fd881908b147e9ec058987f000c2f111a6083c290920cdf28766962b06e0fa94008d78ebe1fb89420ac24b555a587c4496

test:
  secret_key_base: 3481b63f4f90cd5e3256705ba515d2ab7c7244e6fbda9a7cbea89786f9a787827b0ff9abb3a2aa898a5e29791c39befa48d5017e1c243c021e9161f11ba91b06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
